sonar.projectKey=subway-surf
sonar.projectName=Subway Surf
sonar.sourceEncoding=UTF-8

sonar.sources=src
sonar.tests=tests
sonar.test.inclusions=tests/**/*.test.ts

sonar.exclusions=dist/**,node_modules/**,public/**,docs/**,scripts/**,**/*.md,**/*.json

